// ┌──────────────────────────────────────────────────┐
// │  Generated by the Iona Compiler                  │
// │  Version: v0.0.1                                 │
// │  Source: D:\Projects\Iona\tests\iona\app.iona    │
// │  Date: 23/11/2024 17:56:58                       │
// │  Caution: Do not manually edit this file!        │
// └──────────────────────────────────────────────────┘
using Iona.Builtins;
using UnityEngine;

namespace App
{
    public class Test : UnityEngine.MonoBehaviour
    {
        public float value = 0.0f;
        public void Start()
        {
        }

        public void Update()
        {
            value += 1 * Time.deltaTime;
        }
    }

    public static partial class Module
    {
        /// <summary>
        /// This function is defined in D:\Projects\Iona\tests\iona\app.iona at line 17
        /// </summary>
        static public void FreeFunc()
        {
        }
    }
}