// ┌──────────────────────────────────────────────────┐
// │  Generated by the Iona Compiler                  │
// │  Version: v0.0.1                                 │
// │  Source: D:\Projects\Iona\tests\iona\app.iona    │
// │  Date: 08/11/2024 03:04:21                       │
// │  Caution: Do not manually edit this file!        │
// └──────────────────────────────────────────────────┘
using Iona.Builtins;
using UnityEngine;

namespace App
{
    public class Test : UnityEngine.MonoBehaviour
    {
        public nint value = 0;
        public Test(nint value)
        {
            this.value = value;
        }

        public void Update()
        {
            value += 1;
        }
    }
}