// ┌──────────────────────────────────────────────────┐
// │  Generated by the Iona Compiler                  │
// │  Version: v0.0.1                                 │
// │  Source: D:\Projects\Iona\tests\iona\app.iona    │
// │  Date: 01/12/2024 21:33:23                       │
// │  Caution: Do not manually edit this file!        │
// └──────────────────────────────────────────────────┘
using Iona.Builtins;
using UnityEngine;

namespace App
{
    public class DamageTicker : UnityEngine.MonoBehaviour
    {
        public float amount = 5.0f;
        public App.Player player;
        public void Start()
        {
            player = GetComponent<Player>();
        }

        public void Update()
        {
            player.health -= amount + 2;
        }
    }
}