// ┌──────────────────────────────────────────────┐
// │  Generated by the Iona Compiler              │
// │  Version: v0.0.1                             │
// │  Source: GENERATED                           │
// │  Date: 08/11/2024 01:23:42                   │
// │  Caution: Do not manually edit this file!    │
// └──────────────────────────────────────────────┘
