// ┌──────────────────────────────────────────────┐
// │  Generated by the Iona Compiler              │
// │  Version: v0.0.1                             │
// │  Source: GENERATED                           │
// │  Date: 07/11/2024 21:22:38                   │
// │  Caution: Do not manually edit this file!    │
// └──────────────────────────────────────────────┘
namespace App
{
    public static class __free__
    {
        /// <summary>
        /// This function is defined in  at line 11
        /// </summary>
        public static nint add(nint x, nint y)
        {
            return x + x;
        }
    }
}