// ┌─────────────────────────────────────────────────────┐
// │  Generated by the Iona Compiler                     │
// │  Version: v0.0.1                                    │
// │  Source: H:\Projects\Iona\tests\iona\player.iona    │
// │  Date: 14/01/2025 17:36:22                          │
// │  Caution: Do not manually edit this file!           │
// └─────────────────────────────────────────────────────┘
using UnityEngine;

namespace App
{
    public class Player : UnityEngine.MonoBehaviour
    {
        public float health = 100.0f;
        internal void Update()
        {
            health -= 1 * Time.deltaTime;
        }

        internal void OnCollisionEnter(Collision collision)
        {
            var name = collision.gameObject.name;
            gameObject.AddComponent<DamageTicker>();
        }
    }
}