// ┌─────────────────────────────────────────────────────┐
// │  Generated by the Iona Compiler                     │
// │  Version: v0.0.1                                    │
// │  Source: D:\Projects\Iona\tests\iona\player.iona    │
// │  Date: 02/12/2024 19:42:01                          │
// │  Caution: Do not manually edit this file!           │
// └─────────────────────────────────────────────────────┘
using UnityEngine;

namespace App
{
    public class Player : UnityEngine.MonoBehaviour
    {
        public float health = 100.0f;
        internal void OnCollisionEnter(Collision collision)
        {
            var name = collision.gameObject.name;
            this.gameObject.AddComponent<DamageTicker>();
        }
    }
}