// ┌─────────────────────────────────────────────────────┐
// │  Generated by the Iona Compiler                     │
// │  Version: v0.0.1                                    │
// │  Source: D:\Projects\Iona\tests\iona\player.iona    │
// │  Date: 29/11/2024 03:43:01                          │
// │  Caution: Do not manually edit this file!           │
// └─────────────────────────────────────────────────────┘
using Iona.Builtins;
using UnityEngine;

namespace App
{
    public class Player : UnityEngine.MonoBehaviour
    {
        public int health = 100;
        internal void Update()
        {
            health += 5;
        }

        internal void OnCollisionEnter(UnityEngine.Collision collision)
        {
            var name = collision.gameObject.name;
            Debug.Log(name);
        }
    }
}